### ISSUE TITLE
is it still being maintained ? 

### ISSUE THREAD

**Issue by m040601** [thegeocrafter/OSMPTExtractor#1]
Hi, thanks for your work on this tool.
Is it still being maintained.
I cant get it to work (browser:chrome, os:linux)

When hover the mouse pointer over the map, no matter
- how much I zoom  ir or out
- tried continente and ilhas

I cant get nothing selected/picked up to extrract.
The box "MUNICIPIO ESCOLHIDO / Passe sobre um concelho" doesnt pick up anything.
It stays empty.

**Comment by thegeocrafter** [comment]
Hello,

Thanks for reporting this.
The tool and data updates are not maintained anymore, although I have plan
to restart it soon.

I just checked the issue with Firefox (50.1.0) and I can check the data for
different municipalities as well download it.

Can you open your browser developer tools (usually F12) and check on
console for any error and paste it here?

Thank you

Best Regards,
Cumprimentos,

The Geocrafter <http://thegeocrafter.github.io/>
(Fernando Ribeiro)



2017-02-16 9:19 GMT+01:00 somename123 <notifications@github.com>:

**Comment by m040601** [comment]
So i seem to have identified the problem, and have made the whole site load everything needed.

Using the latest stable Chome browser (Version 56.0.2924.87
)on a ARM Linux platform  (chromebook)
I checked the javascript console and started to see lots of warnings about mixing HTTP and HTTPS requests .

For  example:

Mixed Content: The page at 'https://thegeocrafter.github.io/osmpt.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://thegeocrafter.github.io/data/conc_continente.min.geojson'. This content should also be served over HTTPS

or

Mixed Content: The page at 'https://thegeocrafter.github.io/osmpt.html' was loaded over HTTPS, but requested an insecure image 'http://a.tile.osm.org/13/3915/3069.png'. This content should also be served over HTTPS.


Then I went to the browser's address bar, where you have an icon sayng "blocked content or scripts".
I accepted the "load unsafe scripts" and then the whole site worked.

Of course if you're using Chrome you will still be getting a big red notice, "site not secure".
Google has (recently I think) tightened the security warnings a lot on the browser.

So this is what you will get if you visit an https domain (https://thegeocrafter.github.io/osmpt.html) trying to load stuff from other 3rd party plain http domains.
